cloudinary_sdk.settings:
  type: mapping
  label: Settings
  mapping:
    cloudinary_sdk_cloud_name:
      type: string
    cloudinary_sdk_api_key:
      type: string
    cloudinary_sdk_api_secret:
      type: string
